import type { BrickDefinition } from "../domain/brick";
import type { ComposerHints } from "../composer";
import { toCatalogEntry } from "./app-catalog-core";
import type { BrickCatalogEntry } from "./app-types";

const groundedMetadata = (
  interactionIntent: string,
  semanticTags: string[],
  actorClass = "generic",
): NonNullable<BrickDefinition["metadata"]> => ({
  style: "grounded",
  artStyle: "realistic-placeholder",
  semanticTags,
  notes: `Grounded gameplay brick for ${interactionIntent}.`,
  realWorldScale: "1 unit = 1 meter",
  actorClass,
  interactionIntent,
  unitSystem: "metric",
});

const createGameplayEntry = ({
  id,
  name,
  summary,
  packageId,
  category,
  capability,
  aliases,
  slots,
  properties,
  assetDependencies = [],
  defaultAssetBindings = [],
  supportedActorTypes = [],
  stateHints,
  footprintMeters,
  interactionDistanceMeters,
  semanticTags,
  actorClass = "generic",
}: {
  id: string;
  name: string;
  summary: string;
  packageId: string;
  category: string;
  capability: ComposerHints["requiredCapabilities"][number];
  aliases: string[];
  slots: BrickDefinition["slots"];
  properties: BrickDefinition["properties"];
  assetDependencies?: string[];
  defaultAssetBindings?: BrickCatalogEntry["defaultAssetBindings"];
  supportedActorTypes?: string[];
  stateHints: string[];
  footprintMeters: [number, number, number];
  interactionDistanceMeters: number;
  semanticTags: string[];
  actorClass?: string;
}): BrickCatalogEntry =>
  toCatalogEntry(
    {
      id,
      name,
      summary,
      metadata: groundedMetadata(capability, semanticTags, actorClass),
      properties,
      slots,
      ports: [{ id: "on-complete", name: "OnComplete", direction: "output", dataType: "event", description: `Emitted when ${name} completes.` }],
    },
    "builtin",
    {
      packageId,
      category,
      supportedActorTypes,
      assetDependencies,
      defaultAssetBindings,
      composeHints: {
        intentAliases: aliases,
        requiredCapabilities: [capability],
        requiredSlots: slots.filter((slot) => !slot.optional).map((slot) => slot.slotId),
        spaceHints: { footprintMeters, interactionDistanceMeters, facing: "forward" },
        stateHints,
        constraintHints: { requiredActorClass: actorClass, conflictsWith: [] },
      },
    },
  );

const createAssetEntry = ({
  id,
  name,
  summary,
  packageId,
  semanticTags,
  resources,
}: {
  id: string;
  name: string;
  summary: string;
  packageId: string;
  semanticTags: string[];
  resources: BrickCatalogEntry["resources"];
}): BrickCatalogEntry =>
  toCatalogEntry(
    {
      id,
      name,
      summary,
      metadata: groundedMetadata("asset-support", semanticTags),
      properties: [],
      slots: [{ slotId: "resource.catalog", label: "Resource Catalog", optional: false, fallbackAssetRef: "builtin:fate.asset.catalog" }],
      ports: [],
    },
    "builtin",
    {
      packageId,
      packageKind: "asset",
      category: "asset-package",
      resources,
    },
  );

const asset = (id: string, packageId: string, resourceType: string, unityTargetType: string, slotHints: string[]): Record<string, unknown> => ({
  id,
  path: `assets/${id}.placeholder.txt`,
  resource_type: resourceType,
  unity_target_type: unityTargetType,
  license_source: `https://example.local/licenses/${packageId}/${id}`,
  slot_hints: slotHints,
});

export const expandedBuiltinCatalogEntries: BrickCatalogEntry[] = [
  createAssetEntry({
    id: "humanoid-foundation-assets",
    name: "Humanoid Foundation Assets",
    summary: "Baseline humanoid white-box asset package.",
    packageId: "fate.assets.humanoid.foundation",
    semanticTags: ["humanoid", "foundation", "mesh", "anim"],
    resources: [
      asset("humanoid_mesh_main", "fate.assets.humanoid.foundation", "mesh", "Mesh", ["mesh.humanoid", "mesh.primary"]),
      asset("humanoid_body_material", "fate.assets.humanoid.foundation", "material", "Material", ["material.humanoid"]),
      asset("humanoid_locomotion_animset", "fate.assets.humanoid.foundation", "anim", "AnimationClip", ["anim.locomotion"]),
      asset("humanoid_prefab_authoring", "fate.assets.humanoid.foundation", "prefab", "GameObject", ["prefab.humanoid"])
    ],
  }),
  createAssetEntry({
    id: "interaction-prop-assets",
    name: "Interaction Prop Assets",
    summary: "Baseline interaction prop package for pickup, throw, keys, levers, and sockets.",
    packageId: "fate.assets.interaction.props",
    semanticTags: ["interaction", "prop", "pickup", "throw"],
    resources: [
      asset("pickup_socket_binding", "fate.assets.interaction.props", "script_ref", "MonoScript", ["socket.hand"]),
      asset("pickup_highlight_vfx", "fate.assets.interaction.props", "vfx", "VisualEffectAsset", ["fx.pickup"]),
      asset("throw_release_vfx", "fate.assets.interaction.props", "vfx", "VisualEffectAsset", ["fx.throw"]),
      asset("throw_release_audio", "fate.assets.interaction.props", "audio", "AudioClip", ["audio.throw"]),
      asset("key_mesh", "fate.assets.interaction.props", "mesh", "Mesh", ["mesh.key"]),
      asset("lever_mesh", "fate.assets.interaction.props", "mesh", "Mesh", ["mesh.lever"]),
      asset("pressure_plate_mesh", "fate.assets.interaction.props", "mesh", "Mesh", ["mesh.plate"]),
      asset("drop_reward_mesh", "fate.assets.interaction.props", "mesh", "Mesh", ["mesh.drop"]),
      asset("socket_target_binding", "fate.assets.interaction.props", "script_ref", "MonoScript", ["socket.target"]),
      asset("destructible_prop_mesh", "fate.assets.interaction.props", "mesh", "Mesh", ["mesh.prop"])
    ],
  }),
  createAssetEntry({
    id: "ladder-foundation-assets",
    name: "Ladder Foundation Assets",
    summary: "Baseline ladder traversal placeholder package.",
    packageId: "fate.assets.ladder.foundation",
    semanticTags: ["ladder", "climb", "mesh", "anim"],
    resources: [
      asset("ladder_mesh_primary", "fate.assets.ladder.foundation", "mesh", "Mesh", ["mesh"]),
      asset("ladder_anim_climb", "fate.assets.ladder.foundation", "anim", "AnimationClip", ["anim.ladder"])
    ],
  }),
  createGameplayEntry({
    id: "locked-door",
    name: "Locked Door",
    summary: "A keyed door with locked and unlocked states.",
    packageId: "fate.interaction.locked-door",
    category: "interaction",
    capability: "interaction.locked_door",
    aliases: ["locked door", "lock", "钥匙门", "锁门"],
    slots: [
      { slotId: "mesh.primary", label: "Door Mesh", optional: false, fallbackAssetRef: "assetpkg://fate.assets.doors.locks/locked_door_mesh" },
      { slotId: "audio.lock", label: "Lock Audio", optional: true, fallbackAssetRef: "assetpkg://fate.assets.audio.gameplay/door_lock_audio" },
    ],
    properties: [
      { key: "requiresKeyId", label: "Key Id", type: "string", defaultValue: "key_a", description: "Required key id.", group: "Logic" },
      { key: "openAngleDeg", label: "Open Angle", type: "number", defaultValue: 95, description: "Open angle in degrees.", group: "Motion", unit: "deg" },
    ],
    assetDependencies: ["fate.assets.doors.locks", "fate.assets.audio.gameplay"],
    defaultAssetBindings: [{ slotId: "mesh.primary", resourceType: "mesh", assetPackageId: "fate.assets.doors.locks", resourceId: "locked_door_mesh" }],
    stateHints: ["locked", "unlocked", "open"],
    footprintMeters: [1.4, 0.3, 2.3],
    interactionDistanceMeters: 1.5,
    semanticTags: ["door", "locked", "keyed"],
  }),
  createGameplayEntry({
    id: "key-pickup",
    name: "Key Pickup",
    summary: "Collectible key item that unlocks keyed interactions.",
    packageId: "fate.interaction.key-pickup",
    category: "interaction",
    capability: "interaction.key_pickup",
    aliases: ["key", "钥匙", "找钥匙"],
    slots: [{ slotId: "mesh.key", label: "Key Mesh", optional: false, fallbackAssetRef: "assetpkg://fate.assets.interaction.props/key_mesh" }],
    properties: [
      { key: "keyId", label: "Key Id", type: "string", defaultValue: "key_a", description: "Identifier granted on pickup.", group: "Logic" },
      { key: "pickupRadiusM", label: "Pickup Radius", type: "number", defaultValue: 1.2, description: "Pickup radius.", group: "Interaction", unit: "m" },
    ],
    assetDependencies: ["fate.assets.interaction.props"],
    defaultAssetBindings: [{ slotId: "mesh.key", resourceType: "mesh", assetPackageId: "fate.assets.interaction.props", resourceId: "key_mesh" }],
    stateHints: ["available", "collected"],
    footprintMeters: [0.2, 0.2, 0.2],
    interactionDistanceMeters: 1.2,
    semanticTags: ["key", "pickup", "unlock"],
  }),
  createGameplayEntry({
    id: "interaction-button",
    name: "Interaction Button",
    summary: "Pressable button for direct world interactions.",
    packageId: "fate.interaction.button",
    category: "interaction",
    capability: "interaction.button",
    aliases: ["button", "按钮", "按钮开关"],
    slots: [{ slotId: "mesh.button", label: "Button Mesh", optional: false, fallbackAssetRef: "assetpkg://fate.assets.interaction.props/button_mesh" }],
    properties: [{ key: "cooldownSeconds", label: "Cooldown", type: "number", defaultValue: 0.6, description: "Press cooldown.", group: "Logic", unit: "s" }],
    assetDependencies: ["fate.assets.interaction.props"],
    defaultAssetBindings: [{ slotId: "mesh.button", resourceType: "mesh", assetPackageId: "fate.assets.interaction.props", resourceId: "button_mesh" }],
    stateHints: ["idle", "pressed", "cooldown"],
    footprintMeters: [0.3, 0.2, 0.3],
    interactionDistanceMeters: 1.1,
    semanticTags: ["button", "press"],
  }),
  createGameplayEntry({
    id: "lever-switch",
    name: "Lever Switch",
    summary: "Lever-operated interaction for gates and stateful logic.",
    packageId: "fate.interaction.lever",
    category: "interaction",
    capability: "interaction.lever",
    aliases: ["lever", "拉杆", "拨杆"],
    slots: [{ slotId: "mesh.lever", label: "Lever Mesh", optional: false, fallbackAssetRef: "assetpkg://fate.assets.interaction.props/lever_mesh" }],
    properties: [{ key: "holdPosition", label: "Hold Position", type: "boolean", defaultValue: true, description: "Whether the lever stays in the toggled state.", group: "Logic" }],
    assetDependencies: ["fate.assets.interaction.props"],
    defaultAssetBindings: [{ slotId: "mesh.lever", resourceType: "mesh", assetPackageId: "fate.assets.interaction.props", resourceId: "lever_mesh" }],
    stateHints: ["off", "on"],
    footprintMeters: [0.4, 0.3, 0.4],
    interactionDistanceMeters: 1.2,
    semanticTags: ["lever", "toggle"],
  }),
  createGameplayEntry({
    id: "pressure-plate",
    name: "Pressure Plate",
    summary: "Step-triggered floor plate for timed interactions.",
    packageId: "fate.interaction.pressure-plate",
    category: "zone",
    capability: "interaction.pressure_plate",
    aliases: ["pressure plate", "踏板", "压力板"],
    slots: [{ slotId: "mesh.plate", label: "Plate Mesh", optional: false, fallbackAssetRef: "assetpkg://fate.assets.interaction.props/pressure_plate_mesh" }],
    properties: [{ key: "resetDelayS", label: "Reset Delay", type: "number", defaultValue: 0.8, description: "Reset delay.", group: "Logic", unit: "s" }],
    assetDependencies: ["fate.assets.interaction.props"],
    defaultAssetBindings: [{ slotId: "mesh.plate", resourceType: "mesh", assetPackageId: "fate.assets.interaction.props", resourceId: "pressure_plate_mesh" }],
    stateHints: ["idle", "pressed", "resetting"],
    footprintMeters: [1, 0.1, 1],
    interactionDistanceMeters: 0.4,
    semanticTags: ["pressure-plate", "trigger"],
  }),
  createGameplayEntry({
    id: "treasure-chest",
    name: "Treasure Chest",
    summary: "Openable chest that grants item drops or inventory rewards.",
    packageId: "fate.interaction.chest",
    category: "loot",
    capability: "interaction.chest",
    aliases: ["chest", "宝箱", "treasure", "开宝箱"],
    slots: [
      { slotId: "mesh.chest", label: "Chest Mesh", optional: false, fallbackAssetRef: "assetpkg://fate.assets.loot.chests/chest_mesh" },
      { slotId: "audio.open", label: "Open Audio", optional: true, fallbackAssetRef: "assetpkg://fate.assets.audio.gameplay/chest_open_audio" },
    ],
    properties: [{ key: "rewardId", label: "Reward Id", type: "string", defaultValue: "reward_basic", description: "Reward bundle id.", group: "Reward" }],
    assetDependencies: ["fate.assets.loot.chests", "fate.assets.audio.gameplay"],
    defaultAssetBindings: [{ slotId: "mesh.chest", resourceType: "mesh", assetPackageId: "fate.assets.loot.chests", resourceId: "chest_mesh" }],
    stateHints: ["closed", "opened", "looted"],
    footprintMeters: [1, 0.9, 0.9],
    interactionDistanceMeters: 1.4,
    semanticTags: ["chest", "loot", "reward"],
  }),
  createGameplayEntry({
    id: "dialog-trigger",
    name: "Dialog Trigger",
    summary: "Conversation start point for grounded interactions.",
    packageId: "fate.interaction.dialog-trigger",
    category: "interaction",
    capability: "interaction.dialog_trigger",
    aliases: ["dialog", "dialogue", "对话", "交谈"],
    slots: [{ slotId: "ui.prompt", label: "Prompt UI", optional: true, fallbackAssetRef: "builtin:ui.dialog.prompt" }],
    properties: [{ key: "dialogId", label: "Dialog Id", type: "string", defaultValue: "npc_intro", description: "Dialog script id.", group: "Narrative" }],
    stateHints: ["idle", "available", "consumed"],
    footprintMeters: [0.8, 0.8, 1.8],
    interactionDistanceMeters: 2,
    semanticTags: ["dialog", "npc", "narrative"],
  }),
  createGameplayEntry({
    id: "quest-trigger",
    name: "Quest Trigger",
    summary: "Quest or mission activation brick with objective ids.",
    packageId: "fate.interaction.quest-trigger",
    category: "interaction",
    capability: "interaction.quest_trigger",
    aliases: ["quest", "任务", "mission"],
    slots: [{ slotId: "ui.quest", label: "Quest UI", optional: true, fallbackAssetRef: "builtin:ui.quest.prompt" }],
    properties: [{ key: "questId", label: "Quest Id", type: "string", defaultValue: "quest_intro", description: "Quest identifier.", group: "Narrative" }],
    stateHints: ["idle", "armed", "completed"],
    footprintMeters: [1, 1, 1],
    interactionDistanceMeters: 2,
    semanticTags: ["quest", "mission", "trigger"],
  }),
  createGameplayEntry({
    id: "damage-zone",
    name: "Damage Zone",
    summary: "Hazard volume that applies periodic damage.",
    packageId: "fate.interaction.damage-zone",
    category: "zone",
    capability: "interaction.damage_zone",
    aliases: ["damage zone", "危险区", "伤害区", "hazard"],
    slots: [{ slotId: "fx.hazard", label: "Hazard FX", optional: true, fallbackAssetRef: "assetpkg://fate.assets.fx.gameplay/hazard_vfx" }],
    properties: [{ key: "damagePerSecond", label: "Damage/S", type: "number", defaultValue: 20, description: "Damage per second.", group: "Gameplay" }],
    assetDependencies: ["fate.assets.fx.gameplay"],
    defaultAssetBindings: [{ slotId: "fx.hazard", resourceType: "vfx", assetPackageId: "fate.assets.fx.gameplay", resourceId: "hazard_vfx" }],
    stateHints: ["idle", "active"],
    footprintMeters: [3, 0.1, 3],
    interactionDistanceMeters: 0.1,
    semanticTags: ["zone", "damage", "hazard"],
  }),
  createGameplayEntry({
    id: "heal-zone",
    name: "Heal Zone",
    summary: "Recovery volume that restores actor state.",
    packageId: "fate.interaction.heal-zone",
    category: "zone",
    capability: "interaction.heal_zone",
    aliases: ["heal zone", "治疗区", "恢复区"],
    slots: [{ slotId: "fx.heal", label: "Heal FX", optional: true, fallbackAssetRef: "assetpkg://fate.assets.fx.gameplay/heal_vfx" }],
    properties: [{ key: "healPerSecond", label: "Heal/S", type: "number", defaultValue: 12, description: "Heal per second.", group: "Gameplay" }],
    assetDependencies: ["fate.assets.fx.gameplay"],
    defaultAssetBindings: [{ slotId: "fx.heal", resourceType: "vfx", assetPackageId: "fate.assets.fx.gameplay", resourceId: "heal_vfx" }],
    stateHints: ["idle", "active"],
    footprintMeters: [3, 0.1, 3],
    interactionDistanceMeters: 0.1,
    semanticTags: ["zone", "heal", "recovery"],
  }),
  createGameplayEntry({
    id: "item-drop",
    name: "Item Drop",
    summary: "World-space reward drop with simple pickup linkage.",
    packageId: "fate.interaction.item-drop",
    category: "loot",
    capability: "interaction.item_drop",
    aliases: ["drop reward", "掉落", "掉落奖励"],
    slots: [{ slotId: "mesh.drop", label: "Drop Mesh", optional: false, fallbackAssetRef: "assetpkg://fate.assets.interaction.props/drop_reward_mesh" }],
    properties: [{ key: "rewardId", label: "Reward Id", type: "string", defaultValue: "reward_drop_a", description: "Dropped reward id.", group: "Reward" }],
    assetDependencies: ["fate.assets.interaction.props"],
    defaultAssetBindings: [{ slotId: "mesh.drop", resourceType: "mesh", assetPackageId: "fate.assets.interaction.props", resourceId: "drop_reward_mesh" }],
    stateHints: ["hidden", "spawned", "claimed"],
    footprintMeters: [0.4, 0.4, 0.4],
    interactionDistanceMeters: 1.2,
    semanticTags: ["reward", "drop", "loot"],
  }),
  createGameplayEntry({
    id: "inventory-grant",
    name: "Inventory Grant",
    summary: "Adds configured items directly into the inventory flow.",
    packageId: "fate.interaction.inventory-grant",
    category: "loot",
    capability: "interaction.inventory_grant",
    aliases: ["inventory grant", "给予物品", "奖励"],
    slots: [{ slotId: "icon.reward", label: "Reward Icon", optional: true, fallbackAssetRef: "builtin:ui.reward.icon" }],
    properties: [{ key: "inventoryItemId", label: "Item Id", type: "string", defaultValue: "potion_small", description: "Granted item id.", group: "Reward" }],
    stateHints: ["ready", "granted"],
    footprintMeters: [0.2, 0.2, 0.2],
    interactionDistanceMeters: 1,
    semanticTags: ["inventory", "grant", "reward"],
  }),
  createGameplayEntry({
    id: "socket-attach",
    name: "Socket Attach",
    summary: "Attach point for props, keys, and held items.",
    packageId: "fate.interaction.socket-attach",
    category: "interaction",
    capability: "interaction.socket_attach",
    aliases: ["socket attach", "挂点", "附着"],
    slots: [{ slotId: "socket.target", label: "Socket Target", optional: false, fallbackAssetRef: "assetpkg://fate.assets.interaction.props/socket_target_binding" }],
    properties: [{ key: "socketName", label: "Socket Name", type: "string", defaultValue: "right_hand", description: "Socket name.", group: "Attachment" }],
    assetDependencies: ["fate.assets.interaction.props"],
    defaultAssetBindings: [{ slotId: "socket.target", resourceType: "script_ref", assetPackageId: "fate.assets.interaction.props", resourceId: "socket_target_binding" }],
    stateHints: ["empty", "occupied"],
    footprintMeters: [0.1, 0.1, 0.1],
    interactionDistanceMeters: 0.5,
    semanticTags: ["socket", "attach", "prop"],
    actorClass: "humanoid",
  }),
  createGameplayEntry({
    id: "destructible-prop",
    name: "Destructible Prop",
    summary: "Breakable prop with damage and destroyed states.",
    packageId: "fate.interaction.destructible-prop",
    category: "interaction",
    capability: "interaction.destructible_prop",
    aliases: ["destructible", "breakable", "可破坏物", "破坏物件"],
    slots: [{ slotId: "mesh.prop", label: "Prop Mesh", optional: false, fallbackAssetRef: "assetpkg://fate.assets.interaction.props/destructible_prop_mesh" }],
    properties: [{ key: "hitPoints", label: "Hit Points", type: "number", defaultValue: 40, description: "Durability.", group: "Gameplay" }],
    assetDependencies: ["fate.assets.interaction.props"],
    defaultAssetBindings: [{ slotId: "mesh.prop", resourceType: "mesh", assetPackageId: "fate.assets.interaction.props", resourceId: "destructible_prop_mesh" }],
    stateHints: ["intact", "damaged", "destroyed"],
    footprintMeters: [1, 1, 1],
    interactionDistanceMeters: 1.5,
    semanticTags: ["destructible", "prop"],
  }),
  createGameplayEntry({
    id: "guard-enemy",
    name: "Guard Enemy",
    summary: "Grounded guard enemy with alert and chase defaults.",
    packageId: "fate.enemy.guard",
    category: "enemy",
    capability: "enemy.guard",
    aliases: ["guard", "守卫", "看守敌人"],
    slots: [{ slotId: "mesh.enemy", label: "Enemy Mesh", optional: false, fallbackAssetRef: "assetpkg://fate.assets.melee.enemy/guard_mesh" }],
    properties: [{ key: "health", label: "Health", type: "number", defaultValue: 120, description: "Enemy health.", group: "Combat" }],
    assetDependencies: ["fate.assets.melee.enemy"],
    defaultAssetBindings: [{ slotId: "mesh.enemy", resourceType: "mesh", assetPackageId: "fate.assets.melee.enemy", resourceId: "guard_mesh" }],
    stateHints: ["idle", "alert", "chase", "dead"],
    footprintMeters: [0.9, 0.9, 1.9],
    interactionDistanceMeters: 6,
    semanticTags: ["enemy", "guard", "combat"],
    actorClass: "humanoid",
  }),
  createGameplayEntry({
    id: "enemy-melee-attack",
    name: "Enemy Melee Attack",
    summary: "Close-range attack profile for grounded humanoid enemies.",
    packageId: "fate.enemy.melee-attack",
    category: "enemy",
    capability: "enemy.melee_attack",
    aliases: ["melee", "近战", "近战敌人"],
    slots: [{ slotId: "anim.attack", label: "Attack Anim", optional: false, fallbackAssetRef: "assetpkg://fate.assets.melee.enemy/melee_attack_anim" }],
    properties: [{ key: "damage", label: "Damage", type: "number", defaultValue: 24, description: "Attack damage.", group: "Combat" }],
    assetDependencies: ["fate.assets.melee.enemy"],
    defaultAssetBindings: [{ slotId: "anim.attack", resourceType: "anim", assetPackageId: "fate.assets.melee.enemy", resourceId: "melee_attack_anim" }],
    stateHints: ["ready", "windup", "swing", "recover"],
    footprintMeters: [0.8, 0.8, 1.8],
    interactionDistanceMeters: 2.4,
    semanticTags: ["enemy", "melee", "combat"],
    actorClass: "humanoid",
  }),
  createGameplayEntry({
    id: "enemy-ranged-attack",
    name: "Enemy Ranged Attack",
    summary: "Projectile attack profile for grounded ranged enemies.",
    packageId: "fate.enemy.ranged-attack",
    category: "enemy",
    capability: "enemy.ranged_attack",
    aliases: ["ranged", "远程", "射击敌人", "远程敌人"],
    slots: [{ slotId: "anim.shoot", label: "Shoot Anim", optional: false, fallbackAssetRef: "assetpkg://fate.assets.ranged.enemy/ranged_attack_anim" }],
    properties: [{ key: "projectileSpeedMps", label: "Projectile Speed", type: "number", defaultValue: 16, description: "Projectile speed.", group: "Combat", unit: "m/s" }],
    assetDependencies: ["fate.assets.ranged.enemy"],
    defaultAssetBindings: [{ slotId: "anim.shoot", resourceType: "anim", assetPackageId: "fate.assets.ranged.enemy", resourceId: "ranged_attack_anim" }],
    stateHints: ["ready", "aim", "fire", "recover"],
    footprintMeters: [0.8, 0.8, 1.8],
    interactionDistanceMeters: 10,
    semanticTags: ["enemy", "ranged", "combat"],
    actorClass: "humanoid",
  }),
  createGameplayEntry({
    id: "enemy-spawner",
    name: "Enemy Spawner",
    summary: "Spawn point that instantiates configured enemy profiles.",
    packageId: "fate.enemy.spawner",
    category: "enemy",
    capability: "enemy.spawner",
    aliases: ["spawner", "刷怪点", "生成敌人"],
    slots: [{ slotId: "fx.spawn", label: "Spawn FX", optional: true, fallbackAssetRef: "assetpkg://fate.assets.fx.gameplay/spawn_vfx" }],
    properties: [{ key: "spawnCount", label: "Spawn Count", type: "number", defaultValue: 1, description: "Enemies spawned.", group: "Spawn" }],
    assetDependencies: ["fate.assets.fx.gameplay"],
    defaultAssetBindings: [{ slotId: "fx.spawn", resourceType: "vfx", assetPackageId: "fate.assets.fx.gameplay", resourceId: "spawn_vfx" }],
    stateHints: ["idle", "armed", "spent"],
    footprintMeters: [1, 1, 1],
    interactionDistanceMeters: 0.5,
    semanticTags: ["enemy", "spawn"],
  }),
  createGameplayEntry({
    id: "aggro-sensor",
    name: "Aggro Sensor",
    summary: "Perception sensor that raises alert when actors enter range.",
    packageId: "fate.enemy.aggro-sensor",
    category: "enemy",
    capability: "enemy.aggro_sensor",
    aliases: ["aggro", "仇恨", "警戒范围"],
    slots: [{ slotId: "fx.sensor", label: "Sensor FX", optional: true, fallbackAssetRef: "assetpkg://fate.assets.fx.gameplay/sensor_vfx" }],
    properties: [{ key: "radiusMeters", label: "Radius", type: "number", defaultValue: 8, description: "Aggro radius.", group: "Perception", unit: "m" }],
    assetDependencies: ["fate.assets.fx.gameplay"],
    defaultAssetBindings: [{ slotId: "fx.sensor", resourceType: "vfx", assetPackageId: "fate.assets.fx.gameplay", resourceId: "sensor_vfx" }],
    stateHints: ["idle", "tracking"],
    footprintMeters: [0.5, 0.5, 0.5],
    interactionDistanceMeters: 8,
    semanticTags: ["enemy", "sensor", "aggro"],
  }),
  createGameplayEntry({
    id: "loot-drop-table",
    name: "Loot Drop Table",
    summary: "Weighted drop table configuration node.",
    packageId: "fate.loot.drop-table",
    category: "loot",
    capability: "loot.drop_table",
    aliases: ["drop table", "loot table", "掉落表", "战利品表"],
    slots: [{ slotId: "data.table", label: "Drop Table", optional: false, fallbackAssetRef: "builtin:data.drop.table" }],
    properties: [{ key: "tableId", label: "Table Id", type: "string", defaultValue: "drop_table_a", description: "Drop table id.", group: "Reward" }],
    stateHints: ["ready"],
    footprintMeters: [0.2, 0.2, 0.2],
    interactionDistanceMeters: 0.1,
    semanticTags: ["loot", "drop-table"],
  }),
  createGameplayEntry({
    id: "pickup-reward",
    name: "Pickup Reward",
    summary: "Collectible reward node linked to loot outcomes.",
    packageId: "fate.loot.pickup-reward",
    category: "loot",
    capability: "loot.pickup_reward",
    aliases: ["pickup reward", "奖励拾取", "拾取奖励"],
    slots: [{ slotId: "mesh.reward", label: "Reward Mesh", optional: false, fallbackAssetRef: "assetpkg://fate.assets.loot.chests/reward_pickup_mesh" }],
    properties: [{ key: "rewardId", label: "Reward Id", type: "string", defaultValue: "reward_pickup_a", description: "Pickup reward id.", group: "Reward" }],
    assetDependencies: ["fate.assets.loot.chests"],
    defaultAssetBindings: [{ slotId: "mesh.reward", resourceType: "mesh", assetPackageId: "fate.assets.loot.chests", resourceId: "reward_pickup_mesh" }],
    stateHints: ["spawned", "claimed"],
    footprintMeters: [0.3, 0.3, 0.3],
    interactionDistanceMeters: 1.2,
    semanticTags: ["loot", "reward", "pickup"],
  }),
  createAssetEntry({
    id: "humanoid-realistic-assets",
    name: "Humanoid Realistic Assets",
    summary: "Grounded placeholder humanoid asset bundle for realistic third-person layouts.",
    packageId: "fate.assets.humanoid.realistic",
    semanticTags: ["humanoid", "realistic", "mesh", "anim"],
    resources: [
      asset("realistic_humanoid_mesh", "fate.assets.humanoid.realistic", "mesh", "Mesh", ["mesh.humanoid"]),
      asset("realistic_humanoid_material", "fate.assets.humanoid.realistic", "material", "Material", ["material.humanoid"]),
      asset("realistic_humanoid_animset", "fate.assets.humanoid.realistic", "anim", "AnimationClip", ["anim.locomotion"]),
    ],
  }),
  createAssetEntry({
    id: "melee-enemy-assets",
    name: "Melee Enemy Assets",
    summary: "Grounded melee enemy placeholder bundle.",
    packageId: "fate.assets.melee.enemy",
    semanticTags: ["enemy", "melee", "realistic-placeholder"],
    resources: [
      asset("guard_mesh", "fate.assets.melee.enemy", "mesh", "Mesh", ["mesh.enemy"]),
      asset("melee_attack_anim", "fate.assets.melee.enemy", "anim", "AnimationClip", ["anim.attack"]),
      asset("guard_prefab", "fate.assets.melee.enemy", "prefab", "GameObject", ["prefab.enemy"]),
    ],
  }),
  createAssetEntry({
    id: "ranged-enemy-assets",
    name: "Ranged Enemy Assets",
    summary: "Grounded ranged enemy placeholder bundle.",
    packageId: "fate.assets.ranged.enemy",
    semanticTags: ["enemy", "ranged", "realistic-placeholder"],
    resources: [
      asset("ranged_enemy_mesh", "fate.assets.ranged.enemy", "mesh", "Mesh", ["mesh.enemy"]),
      asset("ranged_attack_anim", "fate.assets.ranged.enemy", "anim", "AnimationClip", ["anim.shoot"]),
      asset("ranged_enemy_prefab", "fate.assets.ranged.enemy", "prefab", "GameObject", ["prefab.enemy"]),
    ],
  }),
  createAssetEntry({
    id: "door-lock-assets",
    name: "Door And Lock Assets",
    summary: "Grounded placeholder bundle for locked/openable door interactions.",
    packageId: "fate.assets.doors.locks",
    semanticTags: ["door", "lock", "realistic-placeholder"],
    resources: [
      asset("locked_door_mesh", "fate.assets.doors.locks", "mesh", "Mesh", ["mesh.primary"]),
      asset("locked_door_material", "fate.assets.doors.locks", "material", "Material", ["material.primary"]),
    ],
  }),
  createAssetEntry({
    id: "loot-chest-assets",
    name: "Loot Chest Assets",
    summary: "Grounded placeholder bundle for chests and reward pickups.",
    packageId: "fate.assets.loot.chests",
    semanticTags: ["loot", "chest", "reward"],
    resources: [
      asset("chest_mesh", "fate.assets.loot.chests", "mesh", "Mesh", ["mesh.chest"]),
      asset("reward_pickup_mesh", "fate.assets.loot.chests", "mesh", "Mesh", ["mesh.reward"]),
    ],
  }),
  createAssetEntry({
    id: "gameplay-fx-assets",
    name: "Gameplay FX Assets",
    summary: "Grounded placeholder VFX for hazards, healing, sensors, and spawns.",
    packageId: "fate.assets.fx.gameplay",
    semanticTags: ["vfx", "gameplay", "realistic-placeholder"],
    resources: [
      asset("hazard_vfx", "fate.assets.fx.gameplay", "vfx", "VisualEffectAsset", ["fx.hazard"]),
      asset("heal_vfx", "fate.assets.fx.gameplay", "vfx", "VisualEffectAsset", ["fx.heal"]),
      asset("spawn_vfx", "fate.assets.fx.gameplay", "vfx", "VisualEffectAsset", ["fx.spawn"]),
      asset("sensor_vfx", "fate.assets.fx.gameplay", "vfx", "VisualEffectAsset", ["fx.sensor"]),
    ],
  }),
  createAssetEntry({
    id: "gameplay-audio-assets",
    name: "Gameplay Audio Assets",
    summary: "Grounded placeholder gameplay audio bundle.",
    packageId: "fate.assets.audio.gameplay",
    semanticTags: ["audio", "gameplay", "realistic-placeholder"],
    resources: [
      asset("door_lock_audio", "fate.assets.audio.gameplay", "audio", "AudioClip", ["audio.lock"]),
      asset("chest_open_audio", "fate.assets.audio.gameplay", "audio", "AudioClip", ["audio.open"]),
    ],
  }),
];
