import type { ComposeCapabilityId } from "./types";

export const CAPABILITY_ORDER: ComposeCapabilityId[] = [
  "actor.humanoid",
  "ability.locomotion",
  "interaction.openable_door",
  "interaction.locked_door",
  "interaction.key_pickup",
  "interaction.button",
  "interaction.lever",
  "interaction.pressure_plate",
  "interaction.ladder",
  "interaction.pickup",
  "interaction.throw",
  "interaction.chest",
  "interaction.dialog_trigger",
  "interaction.quest_trigger",
  "interaction.checkpoint",
  "interaction.teleport",
  "interaction.trigger_zone",
  "interaction.damage_zone",
  "interaction.heal_zone",
  "interaction.item_drop",
  "interaction.inventory_grant",
  "interaction.socket_attach",
  "interaction.destructible_prop",
  "enemy.patrol",
  "enemy.guard",
  "enemy.melee_attack",
  "enemy.ranged_attack",
  "enemy.spawner",
  "enemy.aggro_sensor",
  "loot.drop_table",
  "loot.pickup_reward",
];

export const CAPABILITY_ALIASES: Record<ComposeCapabilityId, string[]> = {
  "actor.humanoid": ["角色基础", "character foundation", "humanoid", "character", "player", "avatar", "角色", "主角", "第三人称角色"],
  "ability.locomotion": ["walk", "run", "jump", "move", "movement", "走", "跑", "跳", "移动"],
  "interaction.openable_door": ["door", "open door", "开门", "门", "门禁"],
  "interaction.locked_door": ["locked door", "locked", "lock", "上锁门", "锁门", "门锁"],
  "interaction.key_pickup": ["key", "key pickup", "钥匙", "找钥匙"],
  "interaction.button": ["button", "按钮", "按键开关"],
  "interaction.lever": ["lever", "拉杆", "扳手开关"],
  "interaction.pressure_plate": ["pressure plate", "plate", "踏板", "压力板"],
  "interaction.ladder": ["ladder", "climb", "梯子", "攀爬"],
  "interaction.pickup": ["pickup", "hold", "grab", "拾取", "拿起"],
  "interaction.throw": ["throw", "toss", "投掷", "扔"],
  "interaction.chest": ["chest", "treasure", "宝箱", "开宝箱"],
  "interaction.dialog_trigger": ["dialog", "dialogue", "talk", "对话", "交谈"],
  "interaction.quest_trigger": ["quest", "mission", "任务", "任务触发"],
  "interaction.checkpoint": ["checkpoint", "save point", "检查点", "存档点"],
  "interaction.teleport": ["teleport", "warp", "传送", "瞬移"],
  "interaction.trigger_zone": ["trigger zone", "zone", "触发区", "区域触发"],
  "interaction.damage_zone": ["damage zone", "hazard", "危险区", "伤害区"],
  "interaction.heal_zone": ["heal zone", "healing", "治疗区", "恢复区"],
  "interaction.item_drop": ["drop reward", "item drop", "掉落", "掉落奖励"],
  "interaction.inventory_grant": ["inventory grant", "reward", "奖励", "给予物品"],
  "interaction.socket_attach": ["socket attach", "attach", "挂点", "装配到挂点"],
  "interaction.destructible_prop": ["destructible", "breakable", "可破坏物", "破坏物件"],
  "enemy.patrol": ["enemy patrol", "patrol enemy", "巡逻敌人", "巡逻"],
  "enemy.guard": ["guard", "守卫", "看守敌人"],
  "enemy.melee_attack": ["melee", "近战", "近战敌人"],
  "enemy.ranged_attack": ["ranged", "shoot", "远程", "远程敌人", "射击敌人"],
  "enemy.spawner": ["spawner", "spawn enemy", "刷怪点", "生成敌人"],
  "enemy.aggro_sensor": ["aggro", "awareness", "仇恨", "警戒范围"],
  "loot.drop_table": ["drop table", "loot table", "掉落表", "战利品表"],
  "loot.pickup_reward": ["pickup reward", "reward pickup", "奖励拾取", "拾取奖励"],
};

export const PREFERRED_ENTRY_IDS: Record<ComposeCapabilityId, string> = {
  "actor.humanoid": "humanoid-actor",
  "ability.locomotion": "locomotion-ability",
  "interaction.openable_door": "door",
  "interaction.locked_door": "locked-door",
  "interaction.key_pickup": "key-pickup",
  "interaction.button": "interaction-button",
  "interaction.lever": "lever-switch",
  "interaction.pressure_plate": "pressure-plate",
  "interaction.ladder": "ladder",
  "interaction.pickup": "pickup-interaction",
  "interaction.throw": "throw-interaction",
  "interaction.chest": "treasure-chest",
  "interaction.dialog_trigger": "dialog-trigger",
  "interaction.quest_trigger": "quest-trigger",
  "interaction.checkpoint": "checkpoint",
  "interaction.teleport": "teleport",
  "interaction.trigger_zone": "trigger-zone",
  "interaction.damage_zone": "damage-zone",
  "interaction.heal_zone": "heal-zone",
  "interaction.item_drop": "item-drop",
  "interaction.inventory_grant": "inventory-grant",
  "interaction.socket_attach": "socket-attach",
  "interaction.destructible_prop": "destructible-prop",
  "enemy.patrol": "patrol-guard",
  "enemy.guard": "guard-enemy",
  "enemy.melee_attack": "enemy-melee-attack",
  "enemy.ranged_attack": "enemy-ranged-attack",
  "enemy.spawner": "enemy-spawner",
  "enemy.aggro_sensor": "aggro-sensor",
  "loot.drop_table": "loot-drop-table",
  "loot.pickup_reward": "pickup-reward",
};

export const nodeIdForCapability = (capabilityId: ComposeCapabilityId): string => {
  const shortId = capabilityId.split(".").pop() ?? capabilityId;
  return `${shortId.replace(/[^a-z0-9]+/gi, "-")}-1`;
};
